header: "Resumen semanal de ofertas — Zona Oeste (CM)"
subject: "Ofertas semanales — Zona Oeste (tu sector)"
to_email: "d.iglesias.chsf@gmail.com"
from_email: "d.iglesias.chsf@gmail.com"

output_html: "digest.html"
output_txt: "digest.txt"

lookback_days: 7

feeds:
- "https://RSS_INFOJOBS_RETAIL_1"
  - "https://RSS_INFOJOBS_EDUCACION_FISICA_1"
  - "https://RSS_EMPLEATE_RETAIL_1"
  - "https://RSS_EMPLEATE_EDUCACION_FISICA_1"

include_keywords:
  - "marketing"
  - "digital"
  - "analítica"
  - "retail"
  - "profesor educación física"
  - "management"
  - "retail"
  - "tienda"
  - "dependiente"
  - "vendedor"
  - "encargado"
  - "store manager"
  - "jefe de tienda"
  - "retail manager"
  - "visual merchandiser"
  - "atención al cliente"
  - "comercial retail"
  - "moda"
  - "textil"
  - "calzado"
  - "deportes"
  - "deportivo"
  - "sneakers"
  - "running"
  - "fitness"
  - "gimnasio"
  - "monitor deportivo"
  - "técnico actividades deportivas"
  - "entrenador"
  - "educación física"
  - "profesor educación física"
  - "TSEAS"
  - "TECO"
  - "TAFAD"
  - "JD Ssports"
  - "Adidas"
  - "Nike"
  - "El Corte Inglés"
  - "Sprinter"
  
include_locations:
  - "Pozuelo"
  - "Majadahonda"
  - "Las Rozas"
  - "Boadilla"
  - "Villaviciosa de Odón"
  - "Torrelodones"
  - "Galapagar"
  - "Collado Villalba"
  - "Aravaca"
  - "Moncloa"
  - "Moncloa-Aravaca"

exclude_keywords:
  - "prácticas"
  - "internship"
  - "junior"
