header: "Resumen semanal de ofertas — Zona Oeste (CM)"
subject: "Ofertas semanales — Zona Oeste (tu sector)"
to_email: "xulo_colorado@hotmail.com"
from_email: "xulo_colorado@hotmail.com"

output_html: "digest.html"
output_txt: "digest.txt"

lookback_days: 7

feeds:
  - ""
  - ""

include_keywords:
  - "marketing"
  - "digital"
  - "analítica"

include_locations:
  - "Pozuelo"
  - "Majadahonda"
  - "Las Rozas"
  - "Boadilla"
  - "Villaviciosa de Odón"
  - "Torrelodones"
  - "Galapagar"
  - "Collado Villalba"

exclude_keywords:
  - "prácticas"
  - "internship"
  - "junior"
